name: Build Python App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller --onefile --windowed events/eventMaker.py

      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/eventMaker.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install py2app

      - name: Create setup.py
        run: |
          echo "
from setuptools import setup

APP = ['events/eventMaker.py']
OPTIONS = {
    'argv_emulation': True,
    'packages': ['tkinter'],
}
setup(
    app=APP,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
          " > setup.py

      - name: Build Mac .app
        run: python setup.py py2app

      - name: Upload macOS build
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: dist/EventMaker.app