name: Export Godot Project to HTML5

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Export Godot project to HTML5
        uses: dulvui/godot-4-html-export@v1
        with:
          godot-version: 4.2.2
          working-directory: ./
