name: Export Godot 4 Project to HTML5

on:
  push:
    branches:
      - main

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Export Godot project to HTML5
        uses: glochtefeld/godot-4-web-export@v0.0.2
        with:
          godot-version: 4.2.2
          working-directory: ./